### ISSUE TITLE
Raw image (L0) extraction

### ISSUE THREAD

**Issue by LucaMancaITA** [jmfriedt/sentinel1_level0#1]
Dear jmfriedt,
first of all, I would like to thank you for sharing this amazing work!
I just wanted to ask a clarification regarding the steps needed to obtain the raw image provided in the readme file (the one with range (a.u.) along the x-axis and azimuth (a.u.) along the y axis). I successfully decoded a raw file of Sentinel 1 using the read_file.c (obtaining a list of brc*.bin and result*.bin files) and I have tried to run the read_bin.m file to process them, without success. I am only interesting in obtaining the corresponding raw image not focused L0, starting from the compressed raw Sentinel product. 
Could you please guide me in the steps needed to generate this raw image?

Thank you again for your time!

Luca

**Comment by jmfriedt** [comment]
Correct: the brc* and result* are named with the swath index (10=swath1, 11=swath2, 12=swath 3) for IW datasets, followed by the time (GPS seconds) to differentiate each file as the satellite is flying along its orbit and switching from one swath to another. For results* I also end the name with NQ the number of IQ pairs stored. The read_bin.m requires that twice this last parameter is provided as quads are IQ pairs, the second argument being the number of lines to read (my 8-GB RAM CF19 laptop cannot load and display a whole image as a single dataset, I have to read chunks of images to display). Indeed read_bin.m will try to run the whole processing (range and azimuth compression): the following subset of the script

```Matlab
function sol=read_bin(filename, count, l)
f=fopen(filename,'rb');
t=fread(f,2*l*count,'float');    % dynamically read to avoid filling memory with a huge t
sol=t(1:2:end)+t(2:2:end)*i; % see GNU Radio's read_complex_binary
```
will probably be easier to read: open the file as binary, read float numbers as alternating I and Q, and construct the sol matrix as I+jQ. Having created this vector, you can reshape to generate the matrix with 2*NQ columns and as many lines as your computer can display. The read_bin.m in 2103_europe_results/ is probably easier to grasp than the one in the root directory for this purpose.
Let me know if that solves the issue, best, JM

**Comment by LucaMancaITA** [comment]
Thank you for your reply! 
Just to be sure I have understood correctly: 
I am using the function read_bin_cal shown below (a slight variation of the read_bin function), to build the sol matrix (with size l x count, or equivalently range x azimuth) of complex IQ values:

```matlab
function sol=read_bin_cal(filename, count, l)
% file name, number of complex data to read, line length
% x=read_bin_cal('resultSW92_T1298411052_NQ2951.bin',60,2951*2);
% plot(abs(x(:,32)));hold on; plot(abs(x(:,2)))

pkg load signal

f=fopen(filename,'rb');
if (f<0) v=0;
else
  % fref=37.53472224
  % fs=5/16*4*fref      % case 11 in Range Decimation, p.35 of Packet Protocol Data Unit
  for k=1:count % size(t)(1)   % 6592 = sweep along azimuth for range compression
    t=fread(f,2*l,'float');    % dynamically read to avoid filling memory with a huge t
    t=t(1:2:end)+t(2:2:end)*i; % see GNU Radio's read_complex_binary
    k
    sol(:,k)=t;
  end
% range compression completed
  fclose(f)
end
```


I have just a doubt: when you loop through all the result*.bin of a single swath (i.e. SW10=swath1), the different sol matrices that you have generated are representative of the same portion of region (and so need to be averaged to get the resulting sol matrix of the given swath) or are they representative of different sub-swath, and so need to be appended to generate the final raw swath image?
Thank you again. Best, Luca.

**Comment by jmfriedt** [comment]
The various .bin files are representative of *sequential* data acquisitions of the successive Bursts, so they will not display the same area and should not be averaged, but they represent adjacent regions as indicated by the GPS timestamp (in seconds). I use https://www.andrews.edu/~tzs/timeconv/timeconvert.php to convert GPS time (in seconds) to UTC and check the consistency of the filename with the acquisition time and date.
Best, JM

**Comment by kagalenko-m-b** [comment]
Hello, Jean-Michel,

Thank you for your hard work on decoding sentinel L0 data. Slowly making my way through your program, I got a couple of questions:
* read_file.c uses htons() to convert the byte order, shouldn't that be ntohs()? Doesn't matter on Intel arch, of course.
* PDU specification specifies 3 bits for "Packet Version Number," but shouldn't that be 2 bits? Otherwise you'd have shift to the right 5 bits to get PID

Best wishes
